### ISSUE TITLE
Broken on Ubuntu

### ISSUE THREAD

**Issue by rothgar** [knosmos/cmdpxl#9]
I tried loading this on Ubuntu 20.04 and get the following result in my terminal. I tried with gnome-terminal and kitty terminal and both had similar results. Not sure if there's something I can do to debug.

The flashes and partial menu showing is from when I push `enter` on my keyboard.

![cmdpxl](https://user-images.githubusercontent.com/371796/131079700-4ee34411-3fe0-42a6-9d69-92b8e6ee63eb.gif)

**Comment by knosmos** [comment]
It looks like you're making an image that is too large (something like 30x30 is usually the maximum). I might add support for larger images sometime (for example by being able to pan around) but for now try making a smaller image.

**Comment by douglascdev** [comment]
@knosmos I was confused as well the first the I ran the script and this happened. What do you think of validating if the terminal size is enough to show the image, showing a warning message instead of drawing everything else if the image is bigger than the terminal size + size of the UI? It would have to run the validation after an image is loaded and every time the terminal size changes.

**Comment by knosmos** [comment]
Alright, I've added support for panning around the image, so it should be able to work with larger images now. The pan function is a bit buggy on Ubuntu but it should be usable - give it a try?

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/30610197/131173710-03b7b4bf-4b41-4b21-bbcf-786cf56e522d.gif)

**Comment by douglascdev** [comment]
Oh, so that's what you meant... much simpler and better than my solution, well done :grin:
It's just a bit confusing to move around when in a blank image(and easy to lose track of where your cursor is). When you move the cursor from the initial position to the left, for instance, it looks like it disappeared, while it actually went to the other side of the screen.

**Comment by rothgar** [comment]
Nice! Thanks for fixing that! I included `cmdpxl` on my list of awesome TUI apps https://github.com/rothgar/awesome-tuis
